add multi Y options to nipals
mljs/matrix pull request #122
Opened 2021-04-20 15:18 UTC by josoriom

2021-04-20 16:06 UTC, lpatiny commented
Could you add an explanation about why exactly you want this change ? I don't see difference between. before and after.

2021-04-20 17:34 UTC, josoriom commented
First I removed this part of the code that disables the possibility of an Y with more than one column.
https://github.com/mljs/matrix/blob/master/src/dc/nipals.js#L21-L24

error message for when the maximum number of iterations is reached
https://github.com/josoriom/matrix/blob/master/src/dc/nipals.js#L48-L50

the normalization of loadings as the source code
https://github.com/josoriom/matrix/blob/master/src/dc/nipals.js#L55
source code: https://github.com/jobo322/MetaboMate/blob/master/R/NIPALS_PLS_component.R#L51

and the testcase to compare the results of both codes:
https://github.com/josoriom/matrix/blob/master/src/__tests__/decompositions/nipals.test.js#L97-L124

2021-04-21 03:55 UTC, jwist requested changes
it looks fine to me. The difference is now that we can use a responde vector of more than one dimension, i.e., with multiple columns

2021-04-21 03:55 UTC, jwist commented on src/dc/nipals.js
> -      if (!Y.isColumnVector() || Y.rows !== X.rows) {
I would leave the test, just adapt it so it works for multiple Y

2021-04-21 03:55 UTC, jwist commented on src/dc/nipals.js
> -        throw new Error('Y must be a column vector of length X.rows');
adapt the text of the error message as well to reflect the results of the new test

2021-04-21 03:55 UTC, jwist commented on src/dc/nipals.js
> -      p = p.div(p.norm());
I would leave the normalisation as before, I think this is wrong in the reference code

2021-04-22 20:12 UTC, merged